-- Migration: create core tables for housing FAQ assistant
-- Run with: supabase db push (or apply manually)

-- Enable pgvector extension for embedding vectors
CREATE EXTENSION IF NOT EXISTS vector;

-- Documents table – stores metadata and reference to file in Supabase Storage
CREATE TABLE IF NOT EXISTS documents (
  id UUID PRIMARY KEY,
  filename TEXT NOT NULL,
  original_filename TEXT,
  mime_type TEXT,
  file_size BIGINT,
  storage_path TEXT NOT NULL,      -- Supabase Storage bucket key
  status TEXT NOT NULL CHECK (status IN ('UPLOADED','PROCESSING','READY','ERROR')),
  error_message TEXT,
  category_id UUID,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Parent chunks – optional hierarchical context (e.g., section headings)
CREATE TABLE IF NOT EXISTS parent_chunks (
  id UUID PRIMARY KEY,
  document_id UUID REFERENCES documents(id) ON DELETE CASCADE,
  chunk_index INT NOT NULL,
  content TEXT NOT NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Child chunks – actual searchable pieces with embeddings
CREATE TABLE IF NOT EXISTS document_chunks (
  id UUID PRIMARY KEY,
  document_id UUID REFERENCES documents(id) ON DELETE CASCADE,
  parent_id UUID REFERENCES parent_chunks(id) ON DELETE SET NULL,
  chunk_index INT NOT NULL,
  content TEXT NOT NULL,
  page_number INT,
  embedding VECTOR(1536),  -- dimension matches Gemini Embedding 2 output (1536)
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Categories (optional classification for documents)
CREATE TABLE IF NOT EXISTS categories (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT
);

-- Optional FAQ rows used by keyword search; this project ships no seed data.
CREATE TABLE IF NOT EXISTS faqs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category TEXT,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  keywords TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);


-- Index for efficient ANN search on embeddings
CREATE INDEX IF NOT EXISTS document_chunks_embedding_idx ON document_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- Trigger to auto‑update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_timestamp_before_update
BEFORE UPDATE ON documents
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
